"""
Example Script: Submitting an AutoPulseSynth Quil-T Program to Azure Quantum

This script demonstrates how a physicist would take the `.quil` file generated 
by the AutoPulseSynth web dashboard and submit it directly to Rigetti 
superconducting hardware acting through Microsoft's Azure Quantum platform.

Prerequisites:
  pip install pyquil azure-quantum[pyquil]

Authentication:
  You must be logged into Azure via `az login` with access to a Quantum Workspace 
  that has Rigetti computing enabled.
"""

import os
import argparse
from azure.quantum.workspace import Workspace
from pyquil import Program

def main(quil_file_path: str):
    # 1. Connect to Azure Quantum Workspace
    print("Connecting to Azure Quantum Workspace...")
    workspace = Workspace(
        resource_id="", # Enter your Azure Quantum resource ID here
        location=""     # Enter your Azure region (e.g., 'westus')
    )

    # 2. Select the Rigetti target
    # We use the Quantum Virtual Machine (QVM) for testing. 
    # To run on actual hardware, swap this to 'rigetti.qpu.aspen-m'
    target_id = "rigetti.sim.qvm"
    print(f"Connecting to Rigetti target: {target_id}...")
    target = workspace.get_targets(name=target_id)
    
    # 3. Load the Quil-T pulse program generated by AutoPulseSynth
    if not os.path.exists(quil_file_path):
        raise FileNotFoundError(f"Could not find the downloaded pulse file: {quil_file_path}")
        
    print(f"Loading custom microwave envelope from {quil_file_path}...")
    with open(quil_file_path, "r") as f:
        quil_source = f.read()
        
    # Parse the textual instruction set into a pyQuil program
    program = Program(quil_source)
    
    # Optional: We must explicitly enable pulse-level control when compiling 
    # for the Rigetti cloud execution environment.
    program.wrap_in_numshots_loop(1000)
    
    # 4. Submit the raw pulse to the hardware via Azure
    print(f"Submitting job to Azure Quantum ({target_id})...")
    
    # Submit the job. The Azure platform handles the secure routing of these 
    # pulse instructions to Rigetti's laboratory control systems in California.
    job = target.submit(program, name="AutoPulseSynth_Verification")
    
    print(f"Job successfully submitted! Job ID: {job.id}")
    print("Waiting for physical execution completion...")
    
    # Wait for the dilution refrigerator to execute the sequence
    job.wait_until_completed()
    print("Execution complete!")
    
    # 5. Fetch and analyze the results
    results = job.get_results()
    
    # In our exported Quil-T, we measure Qubit 0 into the bit register 'ro[0]'.
    # We count how many times out of 1000 shots the qubit was physically in state |1>.
    measurements = results.get("ro", [])
    ground_state_count = measurements.count([0])
    excited_state_count = measurements.count([1])
    
    f_achieved = excited_state_count / len(measurements)
    print("--- EXPERIMENT RESULTS ---")
    print(f"Measured |0> : {ground_state_count} shots")
    print(f"Measured |1> : {excited_state_count} shots")
    print(f"Physical Gate Fidelity: {f_achieved * 100:.2f}%")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run an AutoPulse Quil-T file on Azure Quantum.")
    parser.add_argument("file", help="Path to the downloaded .quil file")
    args = parser.parse_args()
    
    # Example usage: python azure_quantum_submit.py x_azure_rigetti.quil
    main(args.file)
